export const workFlow = {
  status: true,
  data: {
    workflowForm: [
      {
        nbName: "外部门称1",
        facilityCode: "202210130001",
        nodeName: "节点1",
        productionMember: "生产人1",
        isBreak: "是",
        detailNodeName: "细化1",
        nodeSec: "秘密",
        location: "位置1",
        gdhId: "XB001S",
        errorDes: "错误描述1",
        testDate: "2023-03-01 14:06:00",
      },
      {
        nbName: "外部门称1",
        facilityCode: "202210130001",
        nodeName: "节点2",
        productionMember: "生产人2",
        isBreak: "是",
        detailNodeName: "细化1",
        nodeSec: "秘密",
        location: "位置1",
        gdhId: "XB001S",
        errorDes: "错误描述1",
        testDate: "2023-2-28 15:06:00",
      },
      {
        nbName: "外部门称2",
        facilityCode: "202210130002",
        nodeName: "节点2",
        productionMember: "生产人2",
        isBreak: "否",
        detailNodeName: "细化2",
        nodeSec: "非密",
        location: "位置2",
        gdhId: "XB002S",
        errorDes: "错误描述2",
        testDate: "测试日期2",
      },
    ],
  },
};
